### ISSUE TITLE
Social Share Links

### ISSUE THREAD

**Issue by qublibjohnny** [QUBLibSys/pic#13]
Add twitter and facebook mini social share icons to accordion results.

Clicking on either should share the text;

"Check out Personal and Institutional Collections - [record name] - [url]"

**Comment by atahir18** [comment]
Done!

**Comment by qublibjohnny** [comment]
Change the shared text so that it links directly to the PIC record, e.g:

"Check out Personal and Institutional Collections - [record name] - [url]"

**Comment by atahir18** [comment]
Updated with Record ID
