### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by qublibjohnny** [QUBLibSys/pic#2]
CSS Considerations;

- remove all inline CSS, use custom.css file for **all** rules 
- ensure comments are included in CSS file where appropriate
- place all media queries at bottom of CSS stylesheet
- check for redundant CSS rules (devtools Web Page Performance > Remove unused CSS)
- validate CSS https://jigsaw.w3.org/css-validator

**Comment by atahir18** [comment]
Complete, validator didn't recognise a translucent color, nothing else.
