### ISSUE TITLE
Configure Contact Form

### ISSUE THREAD

**Issue by qublibjohnny** [QUBLibSys/pic#4]
Configure contact form using [PHP Mailer](https://github.com/PHPMailer/PHPMailer).

There's a Codeigniter library available here that may be useful and easier to integrate https://github.com/ivantcholakov/codeigniter-phpmailer. 

See Johnny for SMTP settings.

**Comment by atahir18** [comment]
PHPMailer now working and form data is valid, flash data added to let user know it's been sent.
