### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by qublibjohnny** [QUBLibSys/pic#7]
Test sample of pages across numerous browsers. Perform searches on each.

Browsers to test;

- Chrome 
- Firefox 
- Safari 
- IE 
- Edge 
- Opera 
- Android
- OSx

**Comment by atahir18** [comment]
TO BE FIXED - DEVICES TESTED
Note 4 - Chrome - Encore URL on results page overflow
	- Too much padding on results card
	- No burger menu at times
	- Jumbotron too large
	- Too much text in 'about' Jumbotron
	- 'TOP' button has white background, needs fixed to dark colour

	- Firefox - Too much padding in search results
	- Samsung Internet - Same as above
	- UC Browser - Above

Nexus 6 - Chrome - All issues same as Note 4
	- Firefox - Padding as above

Moto G5 - Chrome - All issues same as Note 4
	- Firefox - Padding

iPhone 6s - Safari - 'Top' button has white background
			- Padding 

	- Chrome - 'Top' button no colour

Windows - Internet Explorer - 'Top button'
	- Opera - No issues
	- Chrome - No issues

MacOS - Safari - 'Top button'
	Firefox - No issues

**Comment by qublibjohnny** [comment]
Close #11 before implementing these changes @atahir18 then re-visit

**Comment by atahir18** [comment]
Done
