### ISSUE TITLE
Mobile Device Testing

### ISSUE THREAD

**Issue by qublibjohnny** [QUBLibSys/pic#8]
Test application on various devices and screen sizes.

Use combination of Google DevTools Device Mode and real devices available in store.

Useful list of devies to test here https://www.browserstack.com/list-of-browsers-and-platforms?product=live

Market Share info https://www.browserstack.com/test-on-the-right-mobile-devices

**Comment by atahir18** [comment]
Tested on Tab A, Nexus 7, Audit on Chrome Dev shows scripts are taking up loading time, will work on this.

**Comment by atahir18** [comment]
Tested on iPhone X

**Comment by atahir18** [comment]
Nexus 6P

**Comment by atahir18** [comment]
Accessibility Audit Passed

**Comment by atahir18** [comment]
Best Practices and SEO passed
Progressive and Performance Failed

**Comment by atahir18** [comment]
Performance passed after removing unused scripts, I believe the site isn't progressive for the time being.
